sed -i '1i\
import androidx.compose.animation.core.Animatable\
import androidx.compose.animation.core.tween\
import androidx.compose.animation.core.FastOutSlowInEasing\
import androidx.compose.foundation.Image\
import androidx.compose.foundation.layout.Box\
import androidx.compose.foundation.layout.Column\
import androidx.compose.foundation.layout.Spacer\
import androidx.compose.foundation.layout.height\
import androidx.compose.foundation.layout.size\
import androidx.compose.material3.Text\
import androidx.compose.runtime.Composable\
import androidx.compose.runtime.LaunchedEffect\
import androidx.compose.runtime.getValue\
import androidx.compose.runtime.mutableStateOf\
import androidx.compose.runtime.remember\
import androidx.compose.runtime.setValue\
import androidx.compose.ui.Alignment\
import androidx.compose.ui.draw.alpha\
import androidx.compose.ui.draw.scale\
import androidx.compose.ui.res.painterResource\
import androidx.compose.ui.text.font.FontWeight\
import androidx.compose.ui.unit.dp\
import androidx.compose.ui.unit.sp\
import kotlinx.coroutines.delay\
' app/src/main/java/com/example/financetracker/MainActivity.kt
